#!/bin/bash
#@author: xuansinhmedia
export ORACLE_HOME=/usr/lib/oracle/11.2/client64/
export LD_LIBRARY_PATH=$ORACLE_HOME/lib:/usr/lib64
PATH=$PATH:$HOME/bin:/sbin:$ORACLE_HOME/bin
export PATH=/usr/lib/oracle/11.2/client64/bin:$PATH

SQL_RESULTS_ARRAY=( $(
sqlplus -S "beepcall_report/\"Beep@report123\"@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.228.33.27)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = 10.228.33.28)(PORT = 1521))(LOAD_BALANCE = yes)(CONNECT_DATA =(SERVER = SHARED)(SERVICE_NAME = reportdb)))" <<EOF
SET PAGESIZE 0 FEEDBACK OFF VERIFY OFF ECHO OFF SERVEROUT ON TIME OFF TIMING OFF
SELECT a.NUM_BEEP,a.NUM_RECALL,a.TKG,ROUND(a.TKKM_PHUT,0),b.NUM_RECALL,b.TOTAL_DURATION,c.NUM_RECALL,c.TOTAL_DURATION FROM BEEP_NOI_MANG_RESULT a INNER JOIN BEEP_NGOAI_MANG_RESULT b ON a.REVENUE_DAY=b.REVENUE_DAY INNER JOIN BEEP_QUOC_TE_RESULT c ON b.REVENUE_DAY=c.REVENUE_DAY WHERE a.REVENUE_DAY>=TRUNC(SYSDATE-1) AND a.REVENUE_DAY<trunc(sysdate);
quit
EOF
) )

#SQL_ARRAYCOUNT=${#SQL_RESULTS_ARRAY[*]}
#SQL_ARRAYIDX=0

NUM_BEEP=${SQL_RESULTS_ARRAY[0]}
NUM_RECALL=${SQL_RESULTS_ARRAY[1]}
TKG=${SQL_RESULTS_ARRAY[2]}
TKKM_PHUT=${SQL_RESULTS_ARRAY[3]}
F_NUM_RECALL=${SQL_RESULTS_ARRAY[4]}
F_TOTAL_DURATION=${SQL_RESULTS_ARRAY[5]}
I_NUM_RECALL=${SQL_RESULTS_ARRAY[6]}
I_TOTAL_DURATION=${SQL_RESULTS_ARRAY[7]}


sqlplus -S "beepcall/\"Beepcall@123\"@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.228.37.64)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = dbvaspri)))" <<EOF
INSERT INTO NET_BEEPCALL(NUM_BEEP,NUM_RECALL,TKG,TKKM_PHUT,REVENUE_DAY) values ($NUM_BEEP,$NUM_RECALL,$TKG,$TKKM_PHUT,SYSDATE-1);
INSERT INTO FOREIGN_BEEPCALL(NUM_BEEP,NUM_RECALL,TOTAL_DURATION,REVENUE_DAY) SELECT COUNT(*),$F_NUM_RECALL,$F_TOTAL_DURATION,SYSDATE-1 FROM POKE_CALL WHERE LAST_START_WORK >= trunc (sysdate-1) and LAST_START_WORK < trunc (sysdate) AND (res = 180 OR res=200) AND SUBSTR (msisdn, -8) NOT LIKE '33%' AND SUBSTR (msisdn, -8) NOT LIKE '34%';
INSERT INTO INTERNATIONAL_BEEPCALL(NUM_BEEP,NUM_RECALL,TOTAL_DURATION,REVENUE_DAY) SELECT COUNT(*),$I_NUM_RECALL,$I_TOTAL_DURATION,SYSDATE-1 FROM POKE_CALL WHERE LAST_START_WORK >= TRUNC (sysdate-1) and LAST_START_WORK < TRUNC(sysdate) AND (res = 180 OR res=200) AND (LENGTH(CALLER)>11 OR LENGTH(MSISDN)>11) AND (CALLER NOT LIKE '00509%' OR MSISDN NOT LIKE '00509%');
commit;
quit
EOF

exit
